add-highlighter global/ number-lines -hlcursor 

add-highlighter global/ show-matching

set-option global indentwidth 8

set-option global scrolloff 5,5

add-highlighter global/ wrap -word -indent

hook global InsertCompletionShow .* %{
    try  %{
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
    }
}

hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}

